### ISSUE TITLE
Samples do not run correctly on Universal Windows (Windows 10)

### ISSUE THREAD

**Issue by thargy** [xamarin/urho-samples#14]
Building and running Urho.Samples.UWP results in a blank app screen and no errors.  Closing the app doesn't trigger detach from the debugger.

**Comment by EgorBo** [comment]
@thargy are you trying to run it in Windows 10 Mobile or as a desktop app? And also do you use the latest revision of samples?

**Comment by JimSEOW** [comment]
Can you get this simple test UWP UrhoSharp to work?
https://github.com/JimSEOW/UrhoSharpTest

**Comment by EgorBo** [comment]
@JimSEOW answered in https://github.com/xamarin/urho/issues/90

**Comment by thargy** [comment]
Ensuring UWP was run as x86 with a valid pak worked.
