### ISSUE TITLE
Urho.Graphics doesn't contain the member `TakeScreenShot`

### ISSUE THREAD

**Issue by define-private-public** [xamarin/urho-samples#21]
I just grabbed a fresh copy of the repo and tried to run it on OS X.  Upon building, I got a single error because of this line:

https://github.com/xamarin/urho-samples/blob/master/FeatureSamples/Core/Sample.cs#L309

Here are the error details:

```
/Users/ben/Desktop/urho-samples/FeatureSamples/Core/Sample.cs(15,15): Error CS1061: Type `Urho.Graphics' does not contain a definition for `TakeScreenShot' and no extension method `TakeScreenShot' of type `Urho.Graphics' could be found. Are you missing an assembly reference? (CS1061) (Urho.Samples)
```

**Comment by define-private-public** [comment]
I checked the Xamarin documentation for the Graphics class, it's not found anywhere.

https://developer.xamarin.com/api/type/Urho.Graphics/

**Comment by MichalPetryk** [comment]
Hi,
I have the same problem... I'm working on latest version of UrhoSharp.Forms (v1.0.557) from NuGet.

**Comment by EgorBo** [comment]
@define-private-public @MichalPetryk sorry guys, I am updating the package, it will be fixed today.

**Comment by define-private-public** [comment]
Thanks!

**Comment by define-private-public** [comment]
Hi.  Have you posted the update to NuGet yet?  It still says the last update was at the end of May.

**Comment by define-private-public** [comment]
Okay, it builds now.  Thanks!

(I don't see it in the docs though).
