### ISSUE TITLE
Crash running WinForms or WPF

### ISSUE THREAD

**Issue by vans163** [xamarin/urho-samples#23]
Using VS2015, windows 7 SP1 x86, inside VirtualBox with 2d and 3d acceleration disabled.

An exception of type 'System.BadImageFormatException' occurred in Urho.dll but was not handled in user code

Additional information: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Happens in MainWindow.xaml.cs RunGame line 57.
currentApplication = Urho.Application.CreateInstance(value.Type, appOptions);

**Comment by EgorBo** [comment]
@vans163 see this thread: http://forums.xamarin.com/discussion/comment/210348/#Comment_210348

**Comment by vans163** [comment]
Rebuilding the project recopies the 64bit version though, setting a post build script could work but that is a bandaid solution.  I looked but cant find what is responsible for the copy. The references on the projects do not ref mono-urho.dll.

Also simply renaming the dll now gives:

An unhandled exception of type 'System.AccessViolationException' occurred in Urho.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by EgorBo** [comment]
Regarding AVException - which version of UrhoSharp do you use and how?

**Comment by vans163** [comment]
UrhoSharp.1.1.91  
I just checked out this repo, opened urho-samples\FeatureSamples\FeatureSamples.sln in VS2015 Express. The changed the build settings for the projects x86 config to build in Any CPU and not in x64. Then built Urho.Samples and Urho.Samples.WPF. Then ran Urho.Samples.WPF.

**Comment by EgorBo** [comment]
@vans163 I've just opened the same solution, changed platform to x86, renamed mono-urho_32bit.dll to mono-urho.dll (in \FeatureSamples\Bin\Desktop) and ran -- all good. 
So can you confirm you did the same? And can you share your logs from "output" window?

**Comment by vans163** [comment]
Digging into this more. The AV Exception happens on line 58 of MainWindow.xaml.cs on currentApplication.Run();

Inspecting currentApplication.Console shows:
'currentApplication.Console' threw an exception of type 'System.ArgumentException'

Inspecting ..Graphics:
'currentApplication.Graphics' threw an exception of type 'System.InvalidOperationException'

IsLogoVisible:
'((Urho.Samples.Sample)currentApplication).IsLogoVisible' threw an exception of type 'System.NullReferenceException'

Output from running shows:
https://gist.github.com/anonymous/c822dc09dc89e9bf2c8d84773b7be103

**Comment by vans163** [comment]
Yup. Same AV error on x64 VirtualBox. Let me try to enable some 3d acceleration to rule out if its basic OpenGL support.
