### ISSUE TITLE
UrhoSurface within RelativeView fails to rotate on iOS device

### ISSUE THREAD

**Issue by v534** [xamarin/urho-samples#25]
UrhoSurface within a RelativeView rotates fine when rotating an Android device, but does not when rotating an iOS device.

**Comment by EgorBo** [comment]
Fixed by:
https://github.com/xamarin/urho/commit/8e8592c3d91a5a6c6c494c9bc69c62d887512ba2
https://github.com/xamarin/urho/commit/5d443db0230fcf379a72f1ada55bc4d0d5caa8dd
