### ISSUE TITLE
SamplyGame not working on Android Emulator windows.. Loading of resources

### ISSUE THREAD

**Issue by juanfranblanco** [xamarin/urho-samples#27]
I have tried to port the SamplyGame to Xamarin.Forms, but in both Forms and Urho "normal" in Android resource loading does not seem to work.

1st, It will load the resources (Fonts) in SamplyGame if the "assets folder" is set to null, BUT then all the components cannot load either the materials or model on the "start menu". I have tried forcing a path "data/" on those but not solution.

iOS and Desktop work fine. I have not test it yet on Mac the Android emulator

**Comment by EgorBo** [comment]
@juanfranblanco I can't reproduce this issue, can you please provide more details: Xamarin.Android version, Android Emulator info, Windows version.

**Comment by juanfranblanco** [comment]
It was on a fresh install of Vs 2015 update 3, default emulator. Windows Version 10.0.14393 Build 14393

**Comment by EgorBo** [comment]
Added error handling, now all assets issues will throw an unhandled exception with a user-friendly message (the exception can be suppressed).
