### ISSUE TITLE
FormsSample crash when navigating back

### ISSUE THREAD

**Issue by v534** [xamarin/urho-samples#28]
After adding Application.Exit() to the latest FormsSample as discussed in #24, it better handles navigating back, but it still crashes often.  Please see a sample crashed application output below, followed by a successful case for comparison. Alternatively, how could the platform specific FeatureSamples be used as part of a Xamarin Forms page (such as using a custom renderer to embed an UrhoSurface)?

FAILURE:
[UrhoSharp] ProxyStop: Releasing context
[AbsListView] viewType is heaer or footer
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[26,tid=12401,Native,Thread_=0x8eba6800,peer=0x12f6a100,"Thread-64983"]
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[27,tid=12383,Native,Thread*=0x8bfa8e00,peer=0x12ccb7c0,"Thread-64984"]
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[28,tid=12381,Native,Thread_=0x8eba8100,peer=0x12cd3460,"Thread-64985"]
Thread finished:  #22
Thread finished:  #23
[UrhoSharp] ProxyStop: Disposing context
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #24
[Mono] [0x90571930] worker starting
[UrhoSharp] ProxyStop: end
[URHOSHARP] App exited: 0
[Mono] [0x90470930] worker starting
[mono-rt] Stacktrace:
[mono-rt] 
[mono-rt] 
[mono-rt] Attempting native Android stacktrace:
[mono-rt] 
[mono-rt]  at +2508811168 [0x1]
[mono-rt]  at +2508811168 [0x3]
[mono-rt] 
[mono-rt] =================================================================
[mono-rt] Got a SIGSEGV while executing native code. This usually indicates
[mono-rt] a fatal error in the mono runtime or one of the native libraries 
[mono-rt] used by your application.
[mono-rt] =================================================================
[mono-rt] 
[libc] Fatal signal 11 (SIGSEGV), code 2, fault addr 0x12c4b400 in tid 12379 (SDLThread)
[] suspend_thread suspend took 202 ms, which is more than the allowed 200 ms

SUCCESS:
[UrhoSharp] ProxyStop: Releasing context
[Mono] DllImport searching in: 'mono-urho' ('libmono-urho.so').
[Mono] Searching for 'RefCounted_ReleaseRef'.
[Mono] Probing 'RefCounted_ReleaseRef'.
[Mono] Found as 'RefCounted_ReleaseRef'.
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[28,tid=24719,Native,Thread_=0x8dfa3700,peer=0x12d8a340,"Thread-64513"]
[art] Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[29,tid=24705,Native,Thread_=0x8ecf2000,peer=0x12c65100,"Thread-64514"]
Thread finished:  #12
[UrhoSharp] ProxyStop: Disposing context
[UrhoSharp] ProxyStop: end
[URHOSHARP] App exited: 0
[SDL] handleNativeExit
Thread finished:  #11
[AbsListView] viewType is heaer or footer
[AbsListView] viewType is heaer or footer
[AbsListView] viewType is heaer or footer
[AbsListView] viewType is heaer or footer
[Mono] [0x9459e930] worker finishing
Thread finished: <Thread Pool> #4
[Mono] [0x935be930] worker finishing
Thread finished: <Thread Pool> #7

**Comment by EgorBo** [comment]
Was fixed in 86010ea61d19536671d0c254870fb807b2cfcbf3
