### ISSUE TITLE
The SamplyGame.sln won’t build unless you open the FeatureSample.sln first

### ISSUE THREAD

**Issue by jasallen** [xamarin/urho-samples#3]
The SamplyGame.sln won’t build unless you open the FeatureSample.sln first and let it restore packages. Removing the UrhoSharp packages and re-adding them does not help either because there is a hard-coded check for “/FeatureSamples/“ path in SamplyGame.csproj

**Comment by EgorBo** [comment]
Thanks @jasallen now both solutions use separate packages.
