### ISSUE TITLE
Cannot deploy UWP App for Hololens using UrhoSharp Due to ucrtbased.dll issues

### ISSUE THREAD

**Issue by dtrubow** [xamarin/urho-samples#31]
The c++ pieces look to have to compilation issues, one dll in particular.

See http://screencast.com/t/2pzZRvTr9yT

**Comment by EgorBo** [comment]
@dtrubow indeed, this dll is needed for debug mode, as a temp workaround you can find UrhoSharp.HoloLens.targets file in /packages/ folder and remove the line

        <Content Include="$(MSBuildProgramFiles32)\Windows Kits\10\bin\x86\ucrt\ucrtbased.dll">
            <Link>ucrtbased.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

**Comment by EgorBo** [comment]
I'll add a `Condition` for Release mode

**Comment by utekai** [comment]
Thanks for confirming. Where is that file you refer to, or the packages folder?

Using Nuget to obtain urhosharp doesn't provide a packages file, everything is in a project.json.

**Comment by dtrubow** [comment]
Thanks for confirming. Where is the folder you refer to? I'm using nuget to install Urhosharp.Hololens into a uwp solution that is attempted to be deployed to windows store. The only file is project.json that contains reference to urhosharp.hololens.

**Comment by EgorBo** [comment]
@dtrubow ah, indeed. project.json 😄 it should be in the same (with project.json) root directory (*.targets).
