### ISSUE TITLE
SamplyGame: Lambda Expression is not valid

### ISSUE THREAD

**Issue by jamesdang** [xamarin/urho-samples#42]
These two lines are not correct:
 public override int MaxHealth => 50;
 protected override Vector3 CollisionShapeSize => base.CollisionShapeSize * 4;

I am using VS2013. Any ideas?

James

**Comment by EgorBo** [comment]
@jamesdang that is a C#6 feature https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/csharp-6#expression-bodied-function-members 
you need at least VS2015 to compile samples.
