### ISSUE TITLE
Hello Gui close button not working in ios simulator

### ISSUE THREAD

**Issue by jasallen** [xamarin/urho-samples#5]
Says "hello close button" but does not stop the engine

**Comment by jasallen** [comment]
While engine-> exit is a no-op on ios, the subscription isn't even called.  SubscribeToReleased appears to not be working.  Tried with a debug.writeLine to make sure it was not the compiler getting rid of a no-op subscription.

**Comment by EgorBo** [comment]
Fixed with https://github.com/xamarin/urho/issues/86
