### ISSUE TITLE
Update broke Spatial Mapping

### ISSUE THREAD

**Issue by johansvedberg** [xamarin/urho-samples#57]
The new update broke the Spatial Mapping cababilites of the HoloLens, it just makes several copies of the same room - with the wrong orientation.

**Comment by johansvedberg** [comment]
![20180227_141801_hololens](https://user-images.githubusercontent.com/6042963/36730834-0d3f7524-1bc9-11e8-891a-e9a29def78b3.jpg)

**Comment by Apeoholic** [comment]
Check out this issue:
https://github.com/Xamarin/Urho/issues/314
Solved the problem for me.
