### ISSUE TITLE
ARcore sample does not work and crashes

### ISSUE THREAD

**Issue by ybrahem** [xamarin/urho-samples#62]
Hello, i tried to download the sample and getting it to work on my android device (8.0) using Samsung S8, but with no success, as soon as it asks for camera permission the camera feed does not appear and when i click in any giving button it crashes. Can you please help ?

the link for the project : https://github.com/xamarin/urho-samples/tree/master/ARCore

> 

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Failed to compile vertex shader ARCore():
[mono-rt] 0:593: P0001: Extension directive must occur before any non-preprocessor tokens
[mono-rt] 0:597: L0001: Typename expected, found 'samplerExternalOES'. You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
[mono-rt] ApplicationOptions: args -w -p "CoreData;MutantData" -hd -landscape -portrait 
[mono-rt]   at Urho.Application.ThrowUnhandledException (System.Exception exc) [0x000de] in <965326e0f5c24b1cb5201899a33f6f26>:0 
[mono-rt]   at Urho.Runtime.OnNativeCallback (Urho.CallbackType type, System.IntPtr target, System.IntPtr param1, System.Int32 param2, System.String param3) [0x001f3] in <965326e0f5c24b1cb5201899a33f6f26>:0 
[mono-rt]   at (wrapper managed-to-native) Urho.Application.Application_Run(intptr)
[mono-rt]   at Urho.Application.Run () [0x00000] in <965326e0f5c24b1cb5201899a33f6f26>:0 
[mono-rt]   at Urho.Droid.UrhoSurface+<>c__DisplayClass15_0.<SetSdlMain>b__0 (System.IntPtr _) [0x00017] in <965326e0f5c24b1cb5201899a33f6f26>:0
[native] filter_update_base.cc:87 Temporary visual feature update failed when computing its residual and Jacobian.
[native] vio_fault_detector.cc:489 VIO did not use vision constraints.
[native] filter_update_base.cc:87 Mapped visual feature update failed when computing its residual and Jacobian.
[native] filter_update_base.cc:87 Temporary visual feature update failed when computing its residual and Jacobian.
[native] filter_update_base.cc:87 Temporary visual feature update failed when computing its residual and Jacobian.
[native] localization_manager.cc:519 Map tracking detected failure condition that despite good tracking metrics gravity check failed. Reporting corrupted state.
[ViewRootImpl@17acedf[MainActivity]] ViewPostIme pointer 0
[OpenGLRenderer] Failed to set damage region on surface 0x7b8021db90, error=EGL_NOT_INITIALIZED
[libc] Fatal signal 6 (SIGABRT), code -6 in tid 8340 (RenderThread)
> 

>

**Comment by ArnaudMarcille** [comment]
I have the same problem, I've tried to skip the exception with this in MyGame.cs:
```
static MyGame()
{
    UnhandledException += (s, e) =>
    {
        if (Debugger.IsAttached)
            Debugger.Break();
        e.Handled = true;
    };
}
```


This allow me to try the app but the camera isn't working. Like in the following picture, I see a black screen and not the camera view. But the tracking of the model is working.

![Image with black screen](https://user-images.githubusercontent.com/28567558/49460914-c4c21480-f7f2-11e8-9a26-b837cb1896bf.jpg)


And with the catched exception, I get this:
Failed to compile vertex shader ARCore():
0:593: P0001: Extension directive must occur before any non-preprocessor tokens
0:597: L0001: Typename expected, found 'samplerExternalOES'. You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
ApplicationOptions: args -w -p "Assets/CoreData;MutantData" -hd -landscape -portrait 

with no inner exception and no stacktrace.

I've tried to rewrite the application with a simple sphere instead of the monster, I haven't this error but I do not have the camera in background.. (Always a black background) maybe I forgot something?

**Comment by ljmyz** [comment]
Same here. Crash on Droïd. But working fine on iOS if NSCameraUsageDescription is in the plist.

**Comment by MichaSolc** [comment]
I have the same issue here? Anyone found a solution?

**Comment by ArnaudMarcille** [comment]
Hi, after a lot of tests, I thinks that the bug is due to the version of arcore used by urho: the version 1.2. This version doesn't support a lot of devices (today, ArCore is in 1.7 witch support way more devices).
So for me: no solution with urho, I have redirect my attention with the direct implementation of arcore with that projetcs:

- ARCore with unity : https://developers.google.com/ar/develop/unity/quickstart-android

- ARCore builded in c# (I found it on github and replace the builded ARCore package from 1.2 to 1.7) : https://github.com/xamarin/XamarinComponents  into /Android/ARCore and read the file External-Dependency-Info.txt.

Unless UrhoSharp decide to update the arcore version there is no way to make it works on some devices...
If you want to check if your device is supported in the current ARCore version:
https://developers.google.com/ar/discover/supported-devices

**Comment by indiePeeters** [comment]
If this is an issue with the version of ARCore that Urhosharp uses, are there any plans to update the arcore version?

**Comment by Groovy1911** [comment]
Hello,

I had the same issue, so I updated the version of ARCore with 1.7. Unfortunately the bug is still there, now I'm focusing on the update of the SDL used by urho. I hope this will correct the problem. Some already tried ?

**Comment by Groovy1911** [comment]
Hi all,

The problem comes from the CoreData.pak asset. To solve the issue:
1) Download the source https://github.com/xamarin/urho
2) Compile Urho3D for Android --> To generate libmono-urho.so
3) Generate tools of Urho3D or download them https://sourceforge.net/projects/urho3d/files/Urho3D/
4) Generate the new CoreData with PackageTool.exe, example https://urho3d.github.io/documentation/1.4/_tools.html
5) Once you have your new CoreData.pak & libmono-urho.so, edit the file "UrhoSharp.csproj" inthe folder "Bindings\NetStandard" to add "monoandroid81" as target of the solution on Windows.
6) Open the solution Urho.sln
7) If you want to upgrade ARCore, download the aar file from Google.
     7.1) Replace the arcore file that is in the solution by the downloaded one
     7.2) Compile only Urho.Droid.CoreAR by using "BUILD" ONLY not "Rebuild"--> You will have some errors (it's normal). You will find sources to correct into the folder OBJ\DEBUG(or REALEASE)\generated\src"
     7.3) After correcting errors coompile again the solution by suing "BUILD" --> the DLL will be generated correctly
8) Into UrhoSharp normally you can find in "Dependencies" --> MonoAndroid 8.1, now build UrhoSharp
9) Build Urho.Extensions.Droid.ARCore

You can find into the folder BIN all dll you need to avoir the P0001 error and use the lastest version of ARCore, just remove UrhoSharp fro you project then add these DLL.

**Comment by Pequeno0** [comment]
Ran into the same:
"[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Failed to compile vertex shader ARCore():
[mono-rt] 0:593: P0001: Extension directive must occur before any non-preprocessor tokens
[mono-rt] 0:597: L0001: Typename expected, found 'samplerExternalOES'. You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
[mono-rt] ApplicationOptions: args -w -p "CoreData;MutantData" -hd -landscape -portrait"

Figured it didn't happen on an older Android phone. Ran into a million problems trying to follow Groovy1911's suggestion, as I'm on Windows only, and therefore had many troubles actually building Urho for Android. It also seems there is already a CoreData.pak, so I don't know why you'd want to repackage that.

My issue was in fact with the actual shader ARCore.glsl, and with the "samplerExternalOES" and the version of the GLSL of the phone, since 
"#extension GL_OES_EGL_image_external : require" is not supported by GLSL 3, which is the standard on the phone.
Adding "#version 100" in the top of the shader in ARCore.glsl forces the shader compiler to treat it as GLSL 2, where this extension is in fact supported. This instantly solved my issue with not being able to compile the shader. Hope this helps anyone who runs into this problem.

**Comment by redeaglekiller** [comment]
> Ran into the same:
> "[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Failed to compile vertex shader ARCore():
> [mono-rt] 0:593: P0001: Extension directive must occur before any non-preprocessor tokens
> [mono-rt] 0:597: L0001: Typename expected, found 'samplerExternalOES'. You can omit this exception by subscribing to Urho.Application.UnhandledException event and set Handled property to True.
> [mono-rt] ApplicationOptions: args -w -p "CoreData;MutantData" -hd -landscape -portrait"
> 
> Figured it didn't happen on an older Android phone. Ran into a million problems trying to follow Groovy1911's suggestion, as I'm on Windows only, and therefore had many troubles actually building Urho for Android. It also seems there is already a CoreData.pak, so I don't know why you'd want to repackage that.
> 
> My issue was in fact with the actual shader ARCore.glsl, and with the "samplerExternalOES" and the version of the GLSL of the phone, since
> "#extension GL_OES_EGL_image_external : require" is not supported by GLSL 3, which is the standard on the phone.
> Adding "#version 100" in the top of the shader in ARCore.glsl forces the shader compiler to treat it as GLSL 2, where this extension is in fact supported. This instantly solved my issue with not being able to compile the shader. Hope this helps anyone who runs into this problem.

Hi,
Could you please explane exactly how you resolved the problem. I have the same issues described above. I tryed to compile urho from scratch, but the issue remains.

Could someone please repair the package available on nugat? I think it could save some trouble to someone else.

Thank you

**Comment by Groovy1911** [comment]
Hi,
Open CoreData.pak with notepad++ to check that the line "#extension GL_OES_EGL_image_external : require" is before these four one:
#include "Uniforms.glsl"
#include "Samplers.glsl"
#include "Transform.glsl"
#include "ScreenPos.glsl"

If not, then you have to recreate the file CoreData.pak. To do it, follows these steps:
 - Remove CoreData.pak in the folder "Urho3D"
 - Check that this line "#extension GL_OES_EGL_image_external : require" is the first one of the file "CoreData/Shaders/GLSL/ARCore.glsl"
 - Use the tool PackageData.exe to genereta a new CoreData.pak

After that you can continue the process I described.

**Comment by redeaglekiller** [comment]
> Hi,
> Open CoreData.pak with notepad++ to check that the line "#extension GL_OES_EGL_image_external : require" is before these four one:
> #include "Uniforms.glsl"
> #include "Samplers.glsl"
> #include "Transform.glsl"
> #include "ScreenPos.glsl"
> 
> If not, then you have to recreate the file CoreData.pak. To do it, follows these steps:
> 
> * Remove CoreData.pak in the folder "Urho3D"
> * Check that this line "#extension GL_OES_EGL_image_external : require" is the first one of the file "CoreData/Shaders/GLSL/ARCore.glsl"
> * Use the tool PackageData.exe to genereta a new CoreData.pak
> 
> After that you can continue the process I described from the bullet 5.

Hi, thank you for the reply.

**Comment by redeaglekiller** [comment]
I think I have a problem with my building environment or I am using the wrong versions of Visual Studio and Visual Studio for Mac. Which versions do you guys use? Do you have problems building on 2019?

**Comment by Groovy1911** [comment]
Hi,
I did it both with VS 2017 and 2019.
You have this issue when you start your app then switch to AR ?

**Comment by redeaglekiller** [comment]
Hi,
yes I use the default package provided by nuget in UrhoSharp +  UrhoSharp.ARCore (both version 1.9.67). So i decided to test with the urho-samples and I got the same error when the device starts AR.

Then I found this issue thread. But I simply can't build the final dll

**Comment by Groovy1911** [comment]
On which bullet are you blocked ?
Are you on Windows ?

If you are blocked to generate libmono-urho.so and you are on windows, this can help you to generate the final DLL:
1. Install MinGW + addons : gcc & msys & cmake (https://cmake.org/download/ --> Binary distributions: Windows win32-x86 ZIP)
	1. Add to the path
		C:\MinGW\cmake-x.x.x-win32-x86\bin
		C:\MinGW\bin
		ANDROID_NDK = C:\MinGW\android-ndk-r12b
2. Create folders into "urho\Bin\Android":
	arm64-v8a
	armeabi
	armeabi-v7a
	x86
	x86_x64
3. In the file"urho\Urho3D\Source\Source\Urho3D\CMakeLists.txt", replace the line
       - COMMAND for /F %%i in ('dir /B *.o*') do ${CMAKE_COMMAND} -E echo_append %%i" " >>merge.bat
       by this one
       - COMMAND ls *.o* | tr '\\n' ' ' >>merge.bat
4. Start "msys.bat"
5. Start command "make -j5 Android"

Normally the libmono-urho.so will be generate. then continue the process I gave above

**Comment by redeaglekiller** [comment]
> On which bullet are you blocked ?
> Are you on Windows ?
> 
> If you are blocked to generate libmono-urho.so and you are on windows, this can help you to generate the final DLL:
> 
> 1. Install MinGW + addons : gcc & msys & cmake (https://cmake.org/download/ --> Binary distributions: Windows win32-x86 ZIP)
>    
>    1. Add to the path
>       C:\MinGW\cmake-x.x.x-win32-x86\bin
>       C:\MinGW\bin
>       ANDROID_NDK = C:\MinGW\android-ndk-r12b
> 2. Create folders into "urho\Bin\Android":
>    arm64-v8a
>    armeabi
>    armeabi-v7a
>    x86
>    x86_x64
> 3. In the file"urho\Urho3D\Source\Source\Urho3D\CMakeLists.txt", replace the line
>    - COMMAND for /F %%i in ('dir /B _.o_') do ${CMAKE_COMMAND} -E echo_append %%i" " >>merge.bat
>    by this one
>    - COMMAND ls _.o_ | tr '\n' ' ' >>merge.bat
> 4. Start "msys.bat"
> 5. Start command "make -j5 Android"
> 
> Normally the libmono-urho.so will be generate. then continue the process I gave above

I can create libmono-urho.so on Mac (and windows now thank you 👍 )

But I cant't create the UrhoSharp project in Visual Studio 2019.

Step nr. 9 in your list.

I get these errors when I try to build:

`The specified language targets for monoandroid81 is missing. Ensure correct tooling is installed for 'monoandroid'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.CSharp.targets' UrhoSharp`

`The specified language targets for uap10.0.16299 is missing. Ensure correct tooling is installed for 'uap'. Missing: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\WindowsXaml\v16.0\Microsoft.Windows.UI.Xaml.CSharp.targets`

I created an issue thread in the main xamarin/urho repo [https://github.com/xamarin/urho/issues/397#issue-551076716](url) .

**Comment by Groovy1911** [comment]
To fix these problems you can:
- Android: 
         - Edit the file "urho\Bindings\NetStandard\UrhoSharp.csproj" and "urho\Bindings\Forms\UrhoSharp.forms.csproj" by opening them with notepad++
                       On the line 
                          "<TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">netstandard2.0;uap10.0.16299;net45;netcoreapp2.1;portable-net45+win8+wpa81</TargetFrameworks>"
                                Add monoandroidXX (I used monoandroid80, check the version you have on your VS2019) -->
                          "<TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">netstandard2.0;monoandroid80;uap10.0.16299;net45;netcoreapp2.1;portable-net45+win8+wpa81</TargetFrameworks>"
              - Then change the version on this line too:
                       
  <ItemGroup Condition="$(TargetFramework) == 'monoandroid81'"> --> <ItemGroup Condition="$(TargetFramework) == 'monoandroidXX'">



- Uap:
       - If you don't care about uap, remove uap10.0.16299 from the line above and remove the entire block <ItemGroup...> ....</ItemGroup>

**Comment by redeaglekiller** [comment]
> To fix these problems you can:
> 
> * Android:
>   - Edit the file "urho\Bindings\NetStandard\UrhoSharp.csproj" and "urho\Bindings\Forms\UrhoSharp.forms.csproj" by opening them with notepad++
>   On the line
>   "netstandard2.0;uap10.0.16299;net45;netcoreapp2.1;portable-net45+win8+wpa81"
>   Add monoandroidXX (I used monoandroid80, check the version you have on your VS2019) -->
>   "netstandard2.0;monoandroid80;uap10.0.16299;net45;netcoreapp2.1;portable-net45+win8+wpa81"
>   - Then change the version on this line too:
>   
>    -->
> * Uap:
>   - If you don't care about uap, remove uap10.0.16299 from the line above and remove the entire block <ItemGroup...> ....

Thanks Groovy1911 for your support on this.

Now I build everything on Windows but I still can't figure out why VisualStudio2019 can't find monoandroid81 and portable-net45+win8+wpa81 as targets. I tried to use monoandroid80 and monoandroid90 but nothing.

After building libmono-urho.so I just open the Urho.sln and I add monodroid81 to the targets, but still no luck.

**Comment by Groovy1911** [comment]
Too Bad !
Try with VS 2017. If you want I can send you my dll for Android but with the lastest version or ARCore.

**Comment by redeaglekiller** [comment]
I'm going to try with VS2017. Could you please send me the dll anyways. I still have to try if my project is even possible with urho. Thank you so much.

**Comment by redeaglekiller** [comment]
I finally managed to compile the dll using Visual Studio 17.

Thank you Groovy1911.

I think my VS2019 installation was broken

**Comment by Groovy1911** [comment]
Good news

**Comment by redeaglekiller** [comment]
I know it's off topic here, but @Groovy1911

How do I update the core.aar? You say it could be downloaded from Google, but when I get the corear sdk I can't find the aar file.

I guess I have to compile this library as well. If so, how does it work?

Thank you.

**Comment by aaaabcv** [comment]
So...and what about simply providing a fixed nuget package???

**Comment by akema-trebla** [comment]
@Groovy1911  Can you send your working dlls? I only have Visual Studio 2019 and it's not allowing me to compile the Urho project without errors for monoandroid80 as target

**Comment by nodoid** [comment]
> 
> 
> So...and what about simply providing a fixed nuget package???

Well that would be helpful...

**Comment by nodoid** [comment]
@Groovy1911 - any chance of sending me the updated android library? Got an AR book being writen at the minute and need code to run on android. Even if you just upload it to here would help

**Comment by Groovy1911** [comment]
Hello, yes I can send you all my dll.

**Comment by Groovy1911** [comment]
Hello,

I share with you my dll via OneDrive (too heavy for an attachment on github and for an email):
https://1drv.ms/u/s!AhmSDeJqz_zkk5wJBGGbkwgJKvJ4Mw

**Comment by nodoid** [comment]
> 
> Hello, I share with you my dll via OneDrive (too heavy for an attachment on github and for an email): https://1drv.ms/u/s!AhmSDeJqz_zkk5wJBGGbkwgJKvJ4Mw

Thanks - Ive; added these in to my prpject, but am getting the following error

System.Exception: 'Failed to add resource path 'Assets/CoreData'
 Assets must be located in '/Assets/Assets/CoreData'' with 'AndroidAsset' Build Action.'

Any ideas what is causing this or how to fix it?

**Comment by Groovy1911** [comment]
Hello,

Try to add this file into your android project (as AndroidAsset)

[cid:9f908b1c-4189-47f8-ae5b-29351b9eae55]
________________________________
De : Paul Johnson <notifications@github.com>
Envoyé : mercredi 4 novembre 2020 01:24
À : xamarin/urho-samples <urho-samples@noreply.github.com>
Cc : Groovy1911 <roman.gregory@live.fr>; Mention <mention@noreply.github.com>
Objet : Re: [xamarin/urho-samples] ARcore sample does not work and crashes (#62)


Hello, I share with you my dll via OneDrive (too heavy for an attachment on github and for an email): https://1drv.ms/u/s!AhmSDeJqz_zkk5wJBGGbkwgJKvJ4Mw

Thanks - Ive; added these in to my prpject, but am getting the following error

System.Exception: 'Failed to add resource path 'Assets/CoreData'
Assets must be located in '/Assets/Assets/CoreData'' with 'AndroidAsset' Build Action.'

Any ideas what is causing this or how to fix it?

**Comment by nodoid** [comment]
Hi,
> Hello, Try to add this file into your android project (as AndroidAsset) [cid:9f908b1c-4189-47f8-ae5b-29351b9eae55]
> […](#)

You might need to email me it - nothing is showing for it :(

**Comment by Groovy1911** [comment]
[CoreData.zip](https://github.com/xamarin/urho-samples/files/5489890/CoreData.zip)
![Capture](https://user-images.githubusercontent.com/33280769/98155005-e42db480-1ed5-11eb-86fd-d60f3da46be2.PNG)

**Comment by nodoid** [comment]
Getting closer - I can feel it. Just hitting 

Java.Lang.UnsatisfiedLinkError: 'No implementation found for long com.google.ar.core.Session.nativeCreateSessionAndWrapper(android.content.Context) (tried Java_com_google_ar_core_Session_nativeCreateSessionAndWrapper and Java_com_google_ar_core_Session_nativeCreateSessionAndWrapper__Landroid_content_Context_2)'

now

**Comment by Groovy1911** [comment]
Hello nodroid,

The issue might come from the version of ARCore you used. I did my DLL with ARCore 1.12, the current version is 1.21 (November 2020). I gave you the right CoreData.pak & UrhoSharp.dll, so now if you want to always be up ot date with ARCore, you can generate your own UrhoSarp... you can follow these steps:
- Download the project, https://github.com/xamarin/urho
- Start Urho.sln, you will have
![Capture](https://user-images.githubusercontent.com/33280769/99725141-f3575980-2ab4-11eb-934d-ce605c0d2f66.jpg)
- Replace the file arcore-1.1.0.aar by the version you want (https://mvnrepository.com/artifact/com.google.ar/core)
- Be sure the aar file has as "Generation Action" --> LibraryProjectZip
- Then Right click on Urho.Droid.CoreAR then click on "ReBuild solution"(Select debug or release, as you need)
- You will have errors, this is normal.
![Capture2](https://user-images.githubusercontent.com/33280769/99726025-4251be80-2ab6-11eb-876f-7f458087e76a.JPG)

- In the folder obj\Release\generated\src, you can find the source files of ARCore
![Capture3](https://user-images.githubusercontent.com/33280769/99726927-85f8f800-2ab7-11eb-8772-3dd28cfe58ae.JPG)

- Fix compiled erros
- Right click on "Urho.Droid.CoreAR" then "Build". /!\ DO NOT CLICK ON REBUILD SOLUTION
- The first DLL is REady
- Now Generate the DLL "Urho.Extensions.Droid.ARCore", be sure this project used the dll Urho.Droid.CoreAR you just generated

I'm sorry for my english, I'm french and I'm learning english :)
Il will try to generate DLL with the latest version of ARCore (1.21).

Let me know if you want the dll I will generate or if my steps aren't clear enought.

**Comment by nodoid** [comment]
The only errors I'm seeing are on line 140 of AugmentedImage.cs and 158 of AugmentedFace.cs - both are trying to override ICollection<Anchor> with ICollection which gives "type must be ICollection<Anchor> to match overriden member TrackableBase.Anchors 

Everything else looks good though. Any ideas on this one? I'm not that well versed in building bindings :(

**Comment by Groovy1911** [comment]
The methods"n_GetAnchors" & the collection "Anchor" of AugmentedImage & AugmentedFace inherit from "TrackableBase" so get the same return for those methods
In the file AugmentedFace.cs:
Replace:
Line 151 the method--> static IntPtr n_GetAnchors (IntPtr jnienv, IntPtr native__this)
by:
static IntPtr n_GetAnchors (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Google.AR.Core.AugmentedFace> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return global::Android.Runtime.JavaCollection<global::Com.Google.AR.Core.Anchor>.ToLocalJniHandle (__this.Anchors);
		}
Replace:
Line 158 the icollection -->public override unsafe global::System.Collections.ICollection Anchors
by:
public override unsafe global::System.Collections.Generic.ICollection<global::Com.Google.AR.Core.Anchor> Anchors {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.ar.core']/class[@name='AugmentedFace']/method[@name='getAnchors' and count(parameter)=0]"
			[Register ("getAnchors", "()Ljava/util/Collection;", "GetGetAnchorsHandler")]
			get {
				const string __id = "getAnchors.()Ljava/util/Collection;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return global::Android.Runtime.JavaCollection<global::Com.Google.AR.Core.Anchor>.FromJniHandle (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}


In the file AugmentedImage.cs
Replace:
Line 133 the method--> static IntPtr n_GetAnchors (IntPtr jnienv, IntPtr native__this)
by:
static IntPtr n_GetAnchors (IntPtr jnienv, IntPtr native__this)
		{
			var __this = global::Java.Lang.Object.GetObject<global::Com.Google.AR.Core.AugmentedImage> (jnienv, native__this, JniHandleOwnership.DoNotTransfer);
			return global::Android.Runtime.JavaCollection<global::Com.Google.AR.Core.Anchor>.ToLocalJniHandle (__this.Anchors);
		}

Replace:
Line 140 the icollection --> 
by:
public override unsafe global::System.Collections.Generic.ICollection<global::Com.Google.AR.Core.Anchor> Anchors {
			// Metadata.xml XPath method reference: path="/api/package[@name='com.google.ar.core']/class[@name='AugmentedImage']/method[@name='getAnchors' and count(parameter)=0]"
			[Register ("getAnchors", "()Ljava/util/Collection;", "GetGetAnchorsHandler")]
			get {
				const string __id = "getAnchors.()Ljava/util/Collection;";
				try {
					var __rm = _members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, null);
					return global::Android.Runtime.JavaCollection<global::Com.Google.AR.Core.Anchor>.FromJniHandle (__rm.Handle, JniHandleOwnership.TransferLocalRef);
				} finally {
				}
			}
		}
