### ISSUE TITLE
Question about the Device and OS version ARCore compatibilty

### ISSUE THREAD

**Issue by Groovy1911** [xamarin/urho-samples#71]
Hi EgorBo,

I would like to know which devices and OS are currently compatible with ARCore on UrhoSharp ? Or if there is something to be sure the device is supported by UrhoSharp 1.9.6.7 ? Maybe a list of supported devices ? Do you have a plan to fit with the list from Google (link below) ?

According to the google documentation (https://developers.google.com/ar/discover/supported-devices) I'm using "ArCoreApk.Instance.CheckAvailability" to check if the device supports ARCore then "Android.App.Application.Context.PackageManager.GetApplicationInfo" to be sure ARCore is installed on the device and now I'm checking the OS Version "Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.OMr1".

Everything works like a charm on : 
- Xiaomi MI 8 with Android 8.1 and 9.
- OnePlus 6 with Android 8.1.

Doesn't work on:
- Samsung Galaxy Note 9 with Android 9.
- Huawei P20 with android 9
- Samsung S8 edge with Android 8.0
- Samsung A5 with Androdid 8

Probably I'm doing something wrong but I can't find what is my mistake.

ps: You are doing an amazing job on UrhoSharp, thank you very much.

**Comment by utekai** [comment]
> ps: You are doing an amazing job on UrhoSharp, thank you very much.

Perhaps 'did' would be more appropriate instead of 'are doing'.

**Comment by Groovy1911** [comment]
I hope not because this engine is pretty cool.

In fact, unfortunately, I have no mistakes. With all phones, I can move around my 3D object, but for those with which it does not work, the camera is not displayed and so I have an empty background.

**Comment by utekai** [comment]
Is the failure silent? 

Aren't there some sort of errors you can find?

**Comment by Groovy1911** [comment]
Maybe yes the failure is silent because I don't have any exceptions.
If you try the ARCore Sample you can reproduce this issue.

Ah ah ah, when all my phones ring at the same I cry !

**Comment by Groovy1911** [comment]
The version of ARCore used in urho is 1.1, so I updated with the lastest version --> 1.7. I still have the same issu. I can see the 3D model, I can see horizontal surface drown by ARCore but the camera is blank. Do you think the problem could be from SDL version used ?

**Comment by Groovy1911** [comment]
Hello @utekai ,

Finally there is a failure:
"System.Exception: Failed to compile vertex shader ARCore():
0:593: P0001: Extension directive must occur before any non-preprocessor tokens
0:597: L0001: Typename expected, found 'samplerExternalOES'.

Normally this error was solved last year but is still there. Do you have an idea how to solve it again :) ?
