### ISSUE TITLE
SamplyGame not working on real android device

### ISSUE THREAD

**Issue by txchen** [xamarin/urho-samples#8]
I deployed the app onto my Samsung S6, Android 5.1.1, and it is not working correctly.

The graphic freezes, but I think the game logic is running, because soundfx seems correctly.

Is urho on xamarin ready for production use?

**Comment by EgorBo** [comment]
@txchen Can you please check which "Supported architectures" are checked in "Properties/Android Options"?Try again with arm64-v8a enabled and disabled please.

**Comment by txchen** [comment]
@EgorBo thanks! But this does not work for me. I tried different combinations, but cannot find a working one.

**Comment by EgorBo** [comment]
Could be Linker or FXAA3 issue (bot were fixed).
